#!/bin/bash -eu
rm -rf /tmp/testdepot
mkdir /tmp/testdepot
rm -rf /tmp/test
mkdir /tmp/test
cd /tmp/test
export JULIA_DEPOT_PATH=/tmp/testdepot 
julia --project="." -e 'using Pkg; Pkg.add("KiteControllers"); using KiteControllers; KiteControllers.install_examples()'
julia --project -e 'using KiteControllers; __PRECOMPILE__ = true; include("examples/autopilot.jl")'
