#!/bin/bash -eu
rm -rf /tmp/testdepot
mkdir /tmp/testdepot
rm -rf /tmp/test
mkdir /tmp/test
cd /tmp/test
export JULIA_DEPOT_PATH=/tmp/testdepot 
# ~/repos/julia/julia --project="." -e "using Pkg; Pkg.add(\"KiteViewers\"); using KiteViewers"
julia --project="." -e "using Pkg; Pkg.add(\"KiteViewers\"); using KiteViewers; Pkg.test(\"KiteViewers\")"
 
