name = "KiteControllers"
uuid = "b19fd437-5b3a-4cca-b199-c3ded0f20ded"
authors = ["Uwe Fechner <fechner@aenarete.eu> and contributors"]
version = "0.1.0"

[deps]
KiteUtils = "90980105-b163-44e5-ba9f-8b1c83bb0533"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
TestEnv = "1e6cf692-eddd-4d53-88a5-2d735e33781b"

[compat]
KiteUtils = "0.3"
Parameters = "0.12"
TestEnv = "1"
julia = "1.6, 1.7, 1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
